=== Rxxbertx/XML-XSLT-PHPSTORM/xsd/ejer5.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">

    <xsd:element name="clase">

        <xsd:complexType>
            <xsd:sequence>
                <xsd:element ref="alumno" minOccurs="0" maxOccurs="unbounded"/>
            </xsd:sequence>
        </xsd:complexType>


    </xsd:element>

    <xsd:element name="alumno">

        <xsd:complexType>
            <xsd:sequence>

                <xsd:element name="nombre"  type="xsd:string"/>
                <xsd:element name="apellidos"  type="xsd:string"/>
                <xsd:element ref="notas"/>
            </xsd:sequence>
        </xsd:complexType>

    </xsd:element>

      <xsd:element name="notas">

          <xsd:complexType>
              <xsd:sequence>
                  <xsd:element type="valorNota" name="eva1"/>
                  <xsd:element type="valorNota" name="eva2"/>
                  <xsd:element type="valorNota" name="eva3"/>
              </xsd:sequence>
          </xsd:complexType>

      </xsd:element>


    <xsd:simpleType name="valorNota" >
        <xsd:restriction base="xsd:int">
            <xsd:maxInclusive value="10"/>
            <xsd:minInclusive value="0"/>
            <xsd:totalDigits value="2"/>
        </xsd:restriction>
    </xsd:simpleType>




</xsd:schema>

=== Rxxbertx/XML-XSLT-PHPSTORM/XML/ejer5.xml
<?xml version="1.0" encoding="UTF-8"?>

<clase xmlns:xsd="http://www.w3.org/2001/XMLSchema-instance"
       xsd:noNamespaceSchemaLocation="../xsd/ejer5.xsd">

    <alumno>
        <nombre>Juan</nombre>
        <apellidos>Ramos Lopez</apellidos>
        <notas>
            <eva1>4</eva1>
            <eva2>6</eva2>
            <eva3>7</eva3>
        </notas>
    </alumno>
    <alumno>
        <nombre>Ana Maria</nombre>
        <apellidos>Barrios Martín</apellidos>
        <notas>
            <eva1>9</eva1>
            <eva2>8</eva2>
            <eva3>9</eva3>
        </notas>
    </alumno>
    <alumno>
        <nombre>Juan Carlos</nombre>
        <apellidos>Marin Palacios</apellidos>
        <notas>
            <eva1>5</eva1>
            <eva2>3</eva2>
            <eva3>4</eva3>
        </notas>
    </alumno>
    <alumno>
        <nombre>Pedro</nombre>
        <apellidos>Barrios Martín</apellidos>
        <notas>
            <eva1>1</eva1>
            <eva2>5</eva2>
            <eva3>3</eva3>
        </notas>
    </alumno>
</clase>
